name: ci
on: [push, workflow_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: [0, 1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - id: spec
        run: |
          spec=$(ls ./cypress/e2e/**/*.cy.js | jq -R -s 'split("\n") - [""] | [_nwise(length / 4 | ceil)][${{ matrix.chunk }}][]' | xargs echo | sed 's/ /,/g')
          echo "value=$spec" >> $GITHUB_OUTPUT
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          spec: ${{ steps.spec.outputs.value }}